### PR TITLE
Styling of trip feed

### PR DESCRIPTION
**Pull request by adikakade31**
- Trips are shown in card view as in Google Trips app.
- Included location attribute in Trip class to store the location of trip. Previously title was used for that but since title be customized by user there was no specific indication of the destination hence added location. So, you would see blank location for the trips which were created before this update. New trips will have their location shown in the feed.
- Made few changes to the alignment of trip item contents.
- Fixed the scrolling behavior of coordinator layout to completely hide toolbar on scroll in trip feed

### CODE REVIEW

**Comment by adikakade31** [comment]
screenshot_20161203-034113

**Comment by adikakade31** [comment]
screenshot_20161203-034701

**Comment by adikakade31** [comment]
screenshot_20161203-040509

**Comment by heyhuyen** [comment]
Looks great @adikakade31 !

**Pull request merged**
