### PR TITLE
some more styling

### PR DESCRIPTION
**Pull request by heyhuyen**
some partial work for #85 and #98

### CODE REVIEW

**Comment by heyhuyen** [comment]
Used card view to be consistent with the trip feed, but the swipe looks a bit weird, so I'll change it to be flush against the screen.

screen shot 2016-12-03 at 11 17 48 am

**Comment by adikakade31** [comment]
Can the font sizes be smaller for text views on trip feed? They look big and occupy more space. I had done some styling there lilke 12dp for text view with drawable and gray color for font and drawable tint as they cannot be clicked. Also can we not have card view as clickable for places inside story view?

**Comment by adikakade31** [comment]
screenshot_20161203-115244

**Comment by heyhuyen** [comment]
@adikakade31 yeah, sorry! I'll fix in my next iteration. For some reason 12 was showing up really tiny on my emulator but I'll change it back to what you had.

I'm going to update the story view so that click will swipe open the right side menu, since it's not easily discoverable right now.

**Pull request merged**
